In [4]:
#1 Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to
# compute the mean and variance of the elements present in the array.

def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

# Example usage:
N = 5  # Number of dimensions
vector = np.random.rand(N)  # Generating a random feature vector of size N
print("Vector:",vector)
mean, variance = compute_mean_and_variance(vector)
print("Mean of the vector:", mean)
print("Variance of the vector:", variance)


Vector: [0.71051885 0.23939345 0.85683561 0.31948446 0.12133978]
Mean of the vector: 0.4495144276572013
Variance of the vector: 0.08055821464986404


In [5]:
#2 Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to
# compute the Covariance between them.

import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.cov(vector1, vector2, bias=True)[0][1]
    return covariance

# Example usage:
M = 5  # Number of dimensions
N = 100  # Number of samples
# Generating two random feature vectors of size M
vector1 = np.random.rand(1, M)
vector2 = np.random.rand(1, M)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
covariance = compute_covariance(vector1, vector2)
print("Covariance between the two vectors:", covariance)

Vector 1: [[0.11213883 0.28811214 0.49511203 0.03385591 0.25866295]]
Vector 2: [[0.28464524 0.07666789 0.05212985 0.00949733 0.4786605 ]]
Covariance between the two vectors: -0.0020493838268932324


In [6]:
#3 Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

import numpy as np

def compute_correlation(vector1, vector2):
    correlation = np.corrcoef(vector1, vector2)[0, 1]
    return correlation

# Example usage:
N = 5  # Number of dimensions
vector1 = np.random.rand(N)  # Generating a random vector of size N
vector2 = np.random.rand(N)  # Generating another random vector of size N
print("Vector 1:", vector1)
print("Vector 2:", vector2)
correlation = compute_correlation(vector1, vector2)
print("Correlation between vector 1 and vector 2:", correlation)


Vector 1: [0.74689511 0.901589   0.76374201 0.16749704 0.04151512]
Vector 2: [0.78369869 0.94036129 0.95483795 0.68959206 0.44972124]
Correlation between vector 1 and vector 2: 0.9101275773714146


In [7]:
#4 Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th
#entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and
#correlation matrix.

import numpy as np

def compute_covariance_matrix(feature_matrix):
    covariance_matrix = np.cov(feature_matrix)
    return covariance_matrix

def compute_correlation_matrix(feature_matrix):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix

# Example usage:
M = 3  # Number of dimensions/features
N = 5  # Number of samples
feature_matrix = np.random.rand(M, N)  # Generating a random feature matrix of size MxN
print("Feature matrix:")
print(feature_matrix)
covariance_matrix = compute_covariance_matrix(feature_matrix)
print("\nCovariance matrix:")
print(covariance_matrix)
correlation_matrix = compute_correlation_matrix(feature_matrix)
print("\nCorrelation matrix:")
print(correlation_matrix)


Feature matrix:
[[0.96306432 0.27531914 0.96001998 0.42293299 0.85873124]
 [0.6124393  0.66197521 0.79024432 0.96495837 0.00147996]
 [0.07999097 0.64720465 0.28371629 0.79923399 0.8500426 ]]

Covariance matrix:
[[ 0.10476233 -0.04239445 -0.06398727]
 [-0.04239445  0.132854   -0.03463604]
 [-0.06398727 -0.03463604  0.11294854]]

Correlation matrix:
[[ 1.         -0.35935122 -0.58823472]
 [-0.35935122  1.         -0.28274871]
 [-0.58823472 -0.28274871  1.        ]]
