In [ ]:
# 1)Write a NumPy program to multiply two given arrays of same size element-by-
# element.
# First here we Import NumPy library with 'np'
import numpy as np

# Create two NumPy arrays 'nums1' and 'nums2' contain matrices of same size
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])

nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])

# Here we are printing the contents of 'nums1' two arrays
print("Array1:")
print(nums1)

print("Array2:")
print(nums2)

# now we perfom element-wise multiplication of arrays using np.multiply()
# np.multiply operation multiplies corresponding elements of the two arrays
print("\nmultiplication of same size element-by-element gives:")
print(np.multiply(nums1, nums2))


Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

multiplication of same size element-by-element gives:
[[10 15  8]
 [ 3 10 25]]


In [ ]:
# 2)Write a NumPy program to find the missing data in a given array.
# First here we Import NumPy library with 'np'
import numpy as np

# Creating a NumPy array 'nums' with provided values, including NaN (Not a Number)
nums = np.array([[3, 2, np.nan, 1],
                 [10, 12, 10, 9],
                 [5, np.nan, 1, np.nan]])

# To print original array
print("Original array:")
print(nums)

# To indicate missing data we use (NaN) in the array using np.isnan() function
# Using the function we get output and in output True represents NaN Values
print("\nThe he missing data of the given array:")
print(np.isnan(nums))


Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

The he missing data of the given array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
# 3)Write a NumPy program to test whether each element of a 1-D array is also present in
# a second array.
# Import the NumPy library with 'np'
import numpy as np

# Creating 'array1' using NumPy
array1 = np.array([0, 10, 20, 40, 60])

# Printing 'array1'
print("Array1: ", array1)

# Creating 'array2'
array2 = np.array([0,40])

# Printing 'array2'
print("Array2: ", array2)

# Comparing 'array1' with 'array2'
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))



Array1:  [ 0 10 20 40 60]
Array2:  [ 0 40]
Compare each element of array1 and array2
[ True False False  True False]


In [ ]:
# 4)Write a NumPy program to save a NumPy array to a text file.
import numpy as np

# Create a sample NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a text file named "array.txt"
np.savetxt("array.txt", arr, delimiter=",")

print("Array saved to text file successfully!")




Array saved to text file successfully!


In [ ]:
# 5)Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between
#   2.5. and 6.5, inclusive.
# Importing the NumPy library with an alias 'np'
import numpy as np

# Generating an array of 30 evenly spaced values from 2.5 to 6.5 inclusive
x = np.linspace(2.5, 6.5, 30)

# Printing the generated array
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]
